package com.dbms.csmq.model.impact;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 07 16:04:42 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpactSearchListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpactSearchListVOImpl() {
    }

    /**
     * Returns the bind variable value for showImpact.
     * @return bind variable value for showImpact
     */
    public String getshowImpact() {
        return (String)getNamedWhereClauseParam("showImpact");
    }

    /**
     * Sets <code>value</code> for bind variable showImpact.
     * @param value value to bind as showImpact
     */
    public void setshowImpact(String value) {
        setNamedWhereClauseParam("showImpact", value);
    }

    /**
     * Returns the bind variable value for mqType.
     * @return bind variable value for mqType
     */
    public String getmqType() {
        return (String)getNamedWhereClauseParam("mqType");
    }

    /**
     * Sets <code>value</code> for bind variable mqType.
     * @param value value to bind as mqType
     */
    public void setmqType(String value) {
        setNamedWhereClauseParam("mqType", value);
    }


}
