package com.dbms.csmq.model.impact;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 13 16:18:12 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SOCsWithNewPTsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SOCsWithNewPTsVOImpl() {
    }


}
