package com.dbms.csmq.model.service.common.serviceinterface;

import com.dbms.csmq.model.service.common.ViewObjTMSQuerySDO;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.soap.SOAPBinding;

import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import oracle.jbo.common.service.types.AttrCtrlHints;
import oracle.jbo.common.service.types.FindControl;
import oracle.jbo.common.service.types.FindCriteria;
import oracle.jbo.service.errors.ServiceException;

import oracle.webservices.annotations.PortableWebService;
import oracle.webservices.annotations.SDODatabinding;
import oracle.webservices.annotations.async.AsyncWebService;
import oracle.webservices.annotations.async.CallbackMethod;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 22 10:44:44 EDT 2013
// ---------------------------------------------------------------------
@AsyncWebService
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.DOCUMENT)
@PortableWebService(targetNamespace="/com/dbms/csmq/model/service/common/", name="ServiceModuleService", wsdlLocation="com/dbms/csmq/model/service/common/serviceinterface/ServiceModuleService.wsdl")
@SDODatabinding(schemaLocation="com/dbms/csmq/model/service/common/serviceinterface/ServiceModuleService.xsd")
public interface ServiceModuleService {

    public static final String NAME = "{/com/dbms/csmq/model/service/common/}ServiceModuleService";

    @WebMethod(action="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1", operationName="findViewObjTMSQuery1")
    @RequestWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1")
    @ResponseWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1Response")
    @WebResult(name="result")
    @CallbackMethod(exclude=true)
    List<ViewObjTMSQuerySDO> findViewObjTMSQuery1(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/com/dbms/csmq/model/service/common/getDfltCtrlHints", operationName="getDfltCtrlHints")
    @RequestWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="getDfltCtrlHints")
    @ResponseWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="getDfltCtrlHintsResponse")
    @WebResult(name="result")
    @CallbackMethod(exclude=true)
    List<AttrCtrlHints> getDfltCtrlHints(@WebParam(mode = WebParam.Mode.IN, name="viewName")
        String viewName, @WebParam(mode = WebParam.Mode.IN, name="localeName")
        String localeName) throws ServiceException;

    @WebMethod(action="/com/dbms/csmq/model/service/common/getDfltCtrlHintsAsync", operationName="getDfltCtrlHintsAsync")
    @RequestWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="getDfltCtrlHintsAsync")
    @ResponseWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="getDfltCtrlHintsAsyncResponse")
    @WebResult(name="result")
    @Action(input="/com/dbms/csmq/model/service/common/getDfltCtrlHintsAsync", output="/com/dbms/csmq/model/service/common/getDfltCtrlHintsAsyncResponse")
    List<AttrCtrlHints> getDfltCtrlHintsAsync(@WebParam(mode = WebParam.Mode.IN, name="viewName")
        String viewName, @WebParam(mode = WebParam.Mode.IN, name="localeName")
        String localeName) throws ServiceException;

    @WebMethod(action="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1Async", operationName="findViewObjTMSQuery1Async")
    @RequestWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1Async")
    @ResponseWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1AsyncResponse")
    @WebResult(name="result")
    @Action(input="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1Async", output="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1AsyncResponse")
    List<ViewObjTMSQuerySDO> findViewObjTMSQuery1Async(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1ViewObjTMSQueryCriteria", operationName="findViewObjTMSQuery1ViewObjTMSQueryCriteria")
    @RequestWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1ViewObjTMSQueryCriteria")
    @ResponseWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1ViewObjTMSQueryCriteriaResponse")
    @WebResult(name="result")
    @CallbackMethod(exclude=true)
    List<ViewObjTMSQuerySDO> findViewObjTMSQuery1ViewObjTMSQueryCriteria(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="dictContentID")
        String dictContentID, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;

    @WebMethod(action="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsync", operationName="findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsync")
    @RequestWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsync")
    @ResponseWrapper(targetNamespace="/com/dbms/csmq/model/service/common/types/", localName="findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsyncResponse")
    @WebResult(name="result")
    @Action(input="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsync", output="/com/dbms/csmq/model/service/common/findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsyncResponse")
    List<ViewObjTMSQuerySDO> findViewObjTMSQuery1ViewObjTMSQueryCriteriaAsync(@WebParam(mode = WebParam.Mode.IN, name="findCriteria")
        FindCriteria findCriteria, @WebParam(mode = WebParam.Mode.IN, name="dictContentID")
        String dictContentID, @WebParam(mode = WebParam.Mode.IN, name="findControl")
        FindControl findControl) throws ServiceException;
}
