package com.dbms.csmq.model.userAccountsList;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 22 15:14:39 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class userAccountsListVO1Impl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public userAccountsListVO1Impl() {
    }
}
