package com.dbms.csmq.model.hierarchy;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 08 12:25:56 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SmallTreeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SmallTreeVOImpl() {
    }


    /**
     * Returns the bind variable value for scopeFilter.
     * @return bind variable value for scopeFilter
     */
    public String getscopeFilter() {
        return (String)getNamedWhereClauseParam("scopeFilter");
    }

    /**
     * Sets <code>value</code> for bind variable scopeFilter.
     * @param value value to bind as scopeFilter
     */
    public void setscopeFilter(String value) {
        setNamedWhereClauseParam("scopeFilter", value);
    }


    /**
     * Returns the bind variable value for dictContentID.
     * @return bind variable value for dictContentID
     */
    public String getdictContentID() {
        return (String)getNamedWhereClauseParam("dictContentID");
    }

    /**
     * Sets <code>value</code> for bind variable dictContentID.
     * @param value value to bind as dictContentID
     */
    public void setdictContentID(String value) {
        setNamedWhereClauseParam("dictContentID", value);
    }

    /**
     * Returns the bind variable value for maxLevels.
     * @return bind variable value for maxLevels
     */
    public String getmaxLevels() {
        return (String)getNamedWhereClauseParam("maxLevels");
    }

    /**
     * Sets <code>value</code> for bind variable maxLevels.
     * @param value value to bind as maxLevels
     */
    public void setmaxLevels(String value) {
        setNamedWhereClauseParam("maxLevels", value);
    }


    /**
     * Returns the bind variable value for termScopeFilter.
     * @return bind variable value for termScopeFilter
     */
    public String gettermScopeFilter() {
        return (String)getNamedWhereClauseParam("termScopeFilter");
    }

    /**
     * Sets <code>value</code> for bind variable termScopeFilter.
     * @param value value to bind as termScopeFilter
     */
    public void settermScopeFilter(String value) {
        setNamedWhereClauseParam("termScopeFilter", value);
    }

    /**
     * Returns the bind variable value for asOfDate.
     * @return bind variable value for asOfDate
     */
    public String getasOfDate() {
        return (String)getNamedWhereClauseParam("asOfDate");
    }

    /**
     * Sets <code>value</code> for bind variable asOfDate.
     * @param value value to bind as asOfDate
     */
    public void setasOfDate(String value) {
        setNamedWhereClauseParam("asOfDate", value);
    }

    /**
     * Returns the bind variable value for sortKey.
     * @return bind variable value for sortKey
     */
    public String getsortKey() {
        return (String)getNamedWhereClauseParam("sortKey");
    }

    /**
     * Sets <code>value</code> for bind variable sortKey.
     * @param value value to bind as sortKey
     */
    public void setsortKey(String value) {
        setNamedWhereClauseParam("sortKey", value);
    }

    /**
     * Returns the bind variable value for returnPrimLinkPath.
     * @return bind variable value for returnPrimLinkPath
     */
    public String getreturnPrimLinkPath() {
        return (String)getNamedWhereClauseParam("returnPrimLinkPath");
    }

    /**
     * Sets <code>value</code> for bind variable returnPrimLinkPath.
     * @param value value to bind as returnPrimLinkPath
     */
    public void setreturnPrimLinkPath(String value) {
        setNamedWhereClauseParam("returnPrimLinkPath", value);
    }

    /**
     * Returns the bind variable value for activationGroup.
     * @return bind variable value for activationGroup
     */
    public String getactivationGroup() {
        return (String)getNamedWhereClauseParam("activationGroup");
    }

    /**
     * Sets <code>value</code> for bind variable activationGroup.
     * @param value value to bind as activationGroup
     */
    public void setactivationGroup(String value) {
        setNamedWhereClauseParam("activationGroup", value);
    }

    /**
     * Returns the bind variable value for ignorePredict.
     * @return bind variable value for ignorePredict
     */
    public String getignorePredict() {
        return (String)getNamedWhereClauseParam("ignorePredict");
    }

    /**
     * Sets <code>value</code> for bind variable ignorePredict.
     * @param value value to bind as ignorePredict
     */
    public void setignorePredict(String value) {
        setNamedWhereClauseParam("ignorePredict", value);
    }

    /**
     * Returns the bind variable value for dictVersion.
     * @return bind variable value for dictVersion
     */
    public String getdictVersion() {
        return (String)getNamedWhereClauseParam("dictVersion");
    }

    /**
     * Sets <code>value</code> for bind variable dictVersion.
     * @param value value to bind as dictVersion
     */
    public void setdictVersion(String value) {
        setNamedWhereClauseParam("dictVersion", value);
    }
}
