package com.dbms.csmq.model.hierarchy;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jul 08 10:58:04 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SourceTreeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SourceTreeVOImpl() {
    }

    /**
     * Returns the bind variable value for dictContentID.
     * @return bind variable value for dictContentID
     */
    public String getdictContentID() {
        return (String)getNamedWhereClauseParam("dictContentID");
    }

    /**
     * Sets <code>value</code> for bind variable dictContentID.
     * @param value value to bind as dictContentID
     */
    public void setdictContentID(String value) {
        setNamedWhereClauseParam("dictContentID", value);
    }


    /**
     * Returns the bind variable value for scopeFilter.
     * @return bind variable value for scopeFilter
     */
    public String getscopeFilter() {
        return (String)getNamedWhereClauseParam("scopeFilter");
    }

    /**
     * Sets <code>value</code> for bind variable scopeFilter.
     * @param value value to bind as scopeFilter
     */
    public void setscopeFilter(String value) {
        setNamedWhereClauseParam("scopeFilter", value);
    }

    /**
     * Returns the bind variable value for returnPrimLinkPath.
     * @return bind variable value for returnPrimLinkPath
     */
    public String getreturnPrimLinkPath() {
        return (String)getNamedWhereClauseParam("returnPrimLinkPath");
    }

    /**
     * Sets <code>value</code> for bind variable returnPrimLinkPath.
     * @param value value to bind as returnPrimLinkPath
     */
    public void setreturnPrimLinkPath(String value) {
        setNamedWhereClauseParam("returnPrimLinkPath", value);
    }

    /**
     * Returns the bind variable value for sortKey.
     * @return bind variable value for sortKey
     */
    public String getsortKey() {
        return (String)getNamedWhereClauseParam("sortKey");
    }

    /**
     * Sets <code>value</code> for bind variable sortKey.
     * @param value value to bind as sortKey
     */
    public void setsortKey(String value) {
        setNamedWhereClauseParam("sortKey", value);
    }

    /**
     * Returns the bind variable value for dictShortName.
     * @return bind variable value for dictShortName
     */
    public String getdictShortName() {
        return (String)getNamedWhereClauseParam("dictShortName");
    }

    /**
     * Sets <code>value</code> for bind variable dictShortName.
     * @param value value to bind as dictShortName
     */
    public void setdictShortName(String value) {
        setNamedWhereClauseParam("dictShortName", value);
    }

    /**
     * Returns the bind variable value for maxLevels.
     * @return bind variable value for maxLevels
     */
    public String getmaxLevels() {
        return (String)getNamedWhereClauseParam("maxLevels");
    }

    /**
     * Sets <code>value</code> for bind variable maxLevels.
     * @param value value to bind as maxLevels
     */
    public void setmaxLevels(String value) {
        setNamedWhereClauseParam("maxLevels", value);
    }

    /**
     * Returns the bind variable value for narrowScopeOnly.
     * @return bind variable value for narrowScopeOnly
     */
    public String getnarrowScopeOnly() {
        return (String)getNamedWhereClauseParam("narrowScopeOnly");
    }

    /**
     * Sets <code>value</code> for bind variable narrowScopeOnly.
     * @param value value to bind as narrowScopeOnly
     */
    public void setnarrowScopeOnly(String value) {
        setNamedWhereClauseParam("narrowScopeOnly", value);
    }

    /**
     * Returns the bind variable value for ignorePredict.
     * @return bind variable value for ignorePredict
     */
    public String getignorePredict() {
        return (String)getNamedWhereClauseParam("ignorePredict");
    }

    /**
     * Sets <code>value</code> for bind variable ignorePredict.
     * @param value value to bind as ignorePredict
     */
    public void setignorePredict(String value) {
        setNamedWhereClauseParam("ignorePredict", value);
    }
}
