package com.dbms.csmq.model.designee;

import oracle.jbo.server.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 07 14:33:03 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DesigneeModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DesigneeModuleImpl() {
    }

    /**
     * Container's getter for designeeListByMQVO1.
     * @return designeeListByMQVO1
     */
    public designeeListByMQVOImpl getdesigneeListByMQVO1() {
        return (designeeListByMQVOImpl)findViewObject("designeeListByMQVO1");
    }

    /**
     * Container's getter for designeeListVO1.
     * @return designeeListVO1
     */
    public designeeListVOImpl getdesigneeListVO1() {
        return (designeeListVOImpl)findViewObject("designeeListVO1");
    }
}
