package com.dbms.csmq.model.publish;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 16 12:05:15 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjTermsByStateRowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        GroupName {
            public Object get(ViewObjTermsByStateRowImpl obj) {
                return obj.getGroupName();
            }

            public void put(ViewObjTermsByStateRowImpl obj, Object value) {
                obj.setGroupName((String)value);
            }
        }
        ,
        DictNm {
            public Object get(ViewObjTermsByStateRowImpl obj) {
                return obj.getDictNm();
            }

            public void put(ViewObjTermsByStateRowImpl obj, Object value) {
                obj.setDictNm((String)value);
            }
        }
        ,
        Mqterm {
            public Object get(ViewObjTermsByStateRowImpl obj) {
                return obj.getMqterm();
            }

            public void put(ViewObjTermsByStateRowImpl obj, Object value) {
                obj.setMqterm((String)value);
            }
        }
        ,
        State {
            public Object get(ViewObjTermsByStateRowImpl obj) {
                return obj.getState();
            }

            public void put(ViewObjTermsByStateRowImpl obj, Object value) {
                obj.setState((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ViewObjTermsByStateRowImpl object);

        public abstract void put(ViewObjTermsByStateRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GROUPNAME = AttributesEnum.GroupName.index();
    public static final int DICTNM = AttributesEnum.DictNm.index();
    public static final int MQTERM = AttributesEnum.Mqterm.index();
    public static final int STATE = AttributesEnum.State.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjTermsByStateRowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute GroupName.
     * @return the GroupName
     */
    public String getGroupName() {
        return (String) getAttributeInternal(GROUPNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupName.
     * @param value value to set the  GroupName
     */
    public void setGroupName(String value) {
        setAttributeInternal(GROUPNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DictNm.
     * @return the DictNm
     */
    public String getDictNm() {
        return (String) getAttributeInternal(DICTNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DictNm.
     * @param value value to set the  DictNm
     */
    public void setDictNm(String value) {
        setAttributeInternal(DICTNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Mqterm.
     * @return the Mqterm
     */
    public String getMqterm() {
        return (String) getAttributeInternal(MQTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Mqterm.
     * @param value value to set the  Mqterm
     */
    public void setMqterm(String value) {
        setAttributeInternal(MQTERM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute State.
     * @return the State
     */
    public String getState() {
        return (String) getAttributeInternal(STATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute State.
     * @param value value to set the  State
     */
    public void setState(String value) {
        setAttributeInternal(STATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
