package com.dbms.csmq.model.publish;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 16 12:05:15 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjTermsByStateImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjTermsByStateImpl() {
    }

    /**
     * Returns the bind variable value for state.
     * @return bind variable value for state
     */
    public String getstate() {
        return (String)getNamedWhereClauseParam("state");
    }

    /**
     * Sets <code>value</code> for bind variable state.
     * @param value value to bind as state
     */
    public void setstate(String value) {
        setNamedWhereClauseParam("state", value);
    }

    /**
     * Returns the bind variable value for activationGroup.
     * @return bind variable value for activationGroup
     */
    public String getactivationGroup() {
        return (String)getNamedWhereClauseParam("activationGroup");
    }

    /**
     * Sets <code>value</code> for bind variable activationGroup.
     * @param value value to bind as activationGroup
     */
    public void setactivationGroup(String value) {
        setNamedWhereClauseParam("activationGroup", value);
    }
}
