package com.dbms.csmq.model.report;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 04 19:27:43 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjUserListForStateImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjUserListForStateImpl() {
    }
}
