package com.dbms.csmq.model.product.client;

import com.dbms.csmq.model.product.common.ProductModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 29 18:58:50 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductModuleClient extends ApplicationModuleImpl implements ProductModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductModuleClient() {
    }

    public void filterProducts(String searchString, String selectedList) {
        Object _ret =
            this.riInvokeExportedMethod(this,"filterProducts",new String [] {"java.lang.String","java.lang.String"},new Object[] {searchString, selectedList});
        return;
    }
}
