package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 20:26:53 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllLevelsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AllLevelsVOImpl() {
    }
}
