package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 08 15:11:21 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DictionaryModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DictionaryModuleImpl() {
    }

    /**
     * Container's getter for DictionaryVO1.
     * @return DictionaryVO1
     */
    public DictionaryVOImpl getDictionaryVO1() {
        return (DictionaryVOImpl)findViewObject("DictionaryVO1");
    }

    /**
     * Container's getter for LevelsByDictionaryVO1.
     * @return LevelsByDictionaryVO1
     */
    public LevelsByDictionaryVOImpl getLevelsByDictionaryVO1() {
        return (LevelsByDictionaryVOImpl)findViewObject("LevelsByDictionaryVO1");
    }

    /**
     * Container's getter for AllLevelsVO1.
     * @return AllLevelsVO1
     */
    public AllLevelsVOImpl getAllLevelsVO1() {
        return (AllLevelsVOImpl)findViewObject("AllLevelsVO1");
    }

    /**
     * Container's getter for CurrentDictionaryVO1.
     * @return CurrentDictionaryVO1
     */
    public ViewObjectImpl getCurrentDictionaryVO1() {
        return (ViewObjectImpl)findViewObject("CurrentDictionaryVO1");
    }

    /**
     * Container's getter for MedDRAVirtualDictionariesViewObj1.
     * @return MedDRAVirtualDictionariesViewObj1
     */
    public MedDRAVirtualDictionariesViewObjImpl getMedDRAVirtualDictionariesViewObj1() {
        return (MedDRAVirtualDictionariesViewObjImpl)findViewObject("MedDRAVirtualDictionariesViewObj1");
    }
}
