package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun May 08 15:10:50 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DictionaryVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DictionaryVOImpl() {
    }


    /**
     * Returns the bind variable value for defaultDictList.
     * @return bind variable value for defaultDictList
     */
    public String getdefaultDictList() {
        return (String)getNamedWhereClauseParam("defaultDictList");
    }

    /**
     * Sets <code>value</code> for bind variable defaultDictList.
     * @param value value to bind as defaultDictList
     */
    public void setdefaultDictList(String value) {
        setNamedWhereClauseParam("defaultDictList", value);
    }
}
