package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 22:46:43 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelsByDictionaryVODefImpl extends ViewDefImpl {
    public LevelsByDictionaryVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public LevelsByDictionaryVODefImpl() {
    }
}
