package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 22:46:42 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LevelsByDictionaryVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Name {
            public Object get(LevelsByDictionaryVORowImpl obj) {
                return obj.getName();
            }

            public void put(LevelsByDictionaryVORowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        ShortName {
            public Object get(LevelsByDictionaryVORowImpl obj) {
                return obj.getShortName();
            }

            public void put(LevelsByDictionaryVORowImpl obj, Object value) {
                obj.setShortName((String)value);
            }
        }
        ,
        Querytypelevel {
            public Object get(LevelsByDictionaryVORowImpl obj) {
                return obj.getQuerytypelevel();
            }

            public void put(LevelsByDictionaryVORowImpl obj, Object value) {
                obj.setQuerytypelevel((String)value);
            }
        }
        ,
        DefLevelId {
            public Object get(LevelsByDictionaryVORowImpl obj) {
                return obj.getDefLevelId();
            }

            public void put(LevelsByDictionaryVORowImpl obj, Object value) {
                obj.setDefLevelId((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(LevelsByDictionaryVORowImpl object);

        public abstract void put(LevelsByDictionaryVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int NAME = AttributesEnum.Name.index();
    public static final int SHORTNAME = AttributesEnum.ShortName.index();
    public static final int QUERYTYPELEVEL = AttributesEnum.Querytypelevel.index();
    public static final int DEFLEVELID = AttributesEnum.DefLevelId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public LevelsByDictionaryVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShortName.
     * @return the ShortName
     */
    public String getShortName() {
        return (String) getAttributeInternal(SHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShortName.
     * @param value value to set the  ShortName
     */
    public void setShortName(String value) {
        setAttributeInternal(SHORTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Querytypelevel.
     * @return the Querytypelevel
     */
    public String getQuerytypelevel() {
        return (String) getAttributeInternal(QUERYTYPELEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Querytypelevel.
     * @param value value to set the  Querytypelevel
     */
    public void setQuerytypelevel(String value) {
        setAttributeInternal(QUERYTYPELEVEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DefLevelId.
     * @return the DefLevelId
     */
    public String getDefLevelId() {
        return (String) getAttributeInternal(DEFLEVELID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DefLevelId.
     * @param value value to set the  DefLevelId
     */
    public void setDefLevelId(String value) {
        setAttributeInternal(DEFLEVELID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
