package com.dbms.csmq.model.dictionary;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 15:31:07 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MedDRAVirtualDictionariesViewObjImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MedDRAVirtualDictionariesViewObjImpl() {
    }

    /**
     * Returns the bind variable value for meddraBaseDictionary.
     * @return bind variable value for meddraBaseDictionary
     */
    public String getmeddraBaseDictionary() {
        return (String)getNamedWhereClauseParam("meddraBaseDictionary");
    }

    /**
     * Sets <code>value</code> for bind variable meddraBaseDictionary.
     * @param value value to bind as meddraBaseDictionary
     */
    public void setmeddraBaseDictionary(String value) {
        setNamedWhereClauseParam("meddraBaseDictionary", value);
    }
}
