package com.dbms.csmq.model.dictionary;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 27 15:31:07 EST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MedDRAVirtualDictionariesViewObjRowImpl extends ViewRowImpl {

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ShortName {
            public Object get(MedDRAVirtualDictionariesViewObjRowImpl obj) {
                return obj.getShortName();
            }

            public void put(MedDRAVirtualDictionariesViewObjRowImpl obj, Object value) {
                obj.setShortName((String)value);
            }
        }
        ,
        Name {
            public Object get(MedDRAVirtualDictionariesViewObjRowImpl obj) {
                return obj.getName();
            }

            public void put(MedDRAVirtualDictionariesViewObjRowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        ReleaseLabel {
            public Object get(MedDRAVirtualDictionariesViewObjRowImpl obj) {
                return obj.getReleaseLabel();
            }

            public void put(MedDRAVirtualDictionariesViewObjRowImpl obj, Object value) {
                obj.setReleaseLabel((String)value);
            }
        }
        ,
        CutoffDate {
            public Object get(MedDRAVirtualDictionariesViewObjRowImpl obj) {
                return obj.getCutoffDate();
            }

            public void put(MedDRAVirtualDictionariesViewObjRowImpl obj, Object value) {
                obj.setCutoffDate((Date)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MedDRAVirtualDictionariesViewObjRowImpl object);

        public abstract void put(MedDRAVirtualDictionariesViewObjRowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SHORTNAME = AttributesEnum.ShortName.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int RELEASELABEL = AttributesEnum.ReleaseLabel.index();
    public static final int CUTOFFDATE = AttributesEnum.CutoffDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MedDRAVirtualDictionariesViewObjRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ShortName.
     * @return the ShortName
     */
    public String getShortName() {
        return (String) getAttributeInternal(SHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShortName.
     * @param value value to set the  ShortName
     */
    public void setShortName(String value) {
        setAttributeInternal(SHORTNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReleaseLabel.
     * @return the ReleaseLabel
     */
    public String getReleaseLabel() {
        return (String) getAttributeInternal(RELEASELABEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReleaseLabel.
     * @param value value to set the  ReleaseLabel
     */
    public void setReleaseLabel(String value) {
        setAttributeInternal(RELEASELABEL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CutoffDate.
     * @return the CutoffDate
     */
    public Date getCutoffDate() {
        return (Date) getAttributeInternal(CUTOFFDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CutoffDate.
     * @param value value to set the  CutoffDate
     */
    public void setCutoffDate(Date value) {
        setAttributeInternal(CUTOFFDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


}
