package com.dbms.csmq.model.product;

import com.dbms.csmq.model.product.common.ProductModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 11 12:44:30 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductModuleImpl extends ApplicationModuleImpl implements ProductModule {
    /**
     * This is the default constructor (do not remove).
     */
    public ProductModuleImpl() {
    }

    /**
     * Container's getter for ViewObj_ProductList1.
     * @return ViewObj_ProductList1
     */
    public ProductListVOImpl getViewObj_ProductList1() {
        return (ProductListVOImpl)findViewObject("ViewObj_ProductList1");
    }

    /**
     * Container's getter for ProductListByMQ1.
     * @return ProductListByMQ1
     */
    public ViewObjectImpl getProductListByMQ1() {
        return (ViewObjectImpl)findViewObject("ProductListByMQ1");
    }

    /**
     * Container's getter for ProductListByMQVO1.
     * @return ProductListByMQVO1
     */
    public ViewObjectImpl getProductListByMQVO1() {
        return (ViewObjectImpl)findViewObject("ProductListByMQVO1");
    }
    

    
    
    
    
    
}
