package com.dbms.csmq.model.product;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 11 12:41:55 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductListVODefImpl extends ViewDefImpl {
    public ProductListVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public ProductListVODefImpl() {
    }
}
