package com.dbms.csmq.model.product;

import oracle.jbo.RowSet;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 20 17:20:23 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductListByMQVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        product {
            public Object get(ProductListByMQVORowImpl obj) {
                return obj.getproduct();
            }

            public void put(ProductListByMQVORowImpl obj, Object value) {
                obj.setproduct((String)value);
            }
        }
        ,
        ProductListByMQVO1 {
            public Object get(ProductListByMQVORowImpl obj) {
                return obj.getProductListByMQVO1();
            }

            public void put(ProductListByMQVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ProductListByMQVORowImpl object);

        public abstract void put(ProductListByMQVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PRODUCT = AttributesEnum.product.index();
    public static final int PRODUCTLISTBYMQVO1 = AttributesEnum.ProductListByMQVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductListByMQVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute product.
     * @return the product
     */
    public String getproduct() {
        return (String) getAttributeInternal(PRODUCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute product.
     * @param value value to set the  product
     */
    public void setproduct(String value) {
        setAttributeInternal(PRODUCT, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductListByMQVO1.
     */
    public RowSet getProductListByMQVO1() {
        return (RowSet)getAttributeInternal(PRODUCTLISTBYMQVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
