package com.dbms.csmq.model.diff;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Mar 21 11:42:41 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DiffModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DiffModuleImpl() {
    }

    /**
     * Container's getter for MQListVO1.
     * @return MQListVO1
     */
    public ViewObjectImpl getMQListLeftVO1() {
        return (ViewObjectImpl)findViewObject("MQListLeftVO1");
    }

    /**
     * Container's getter for DirectRelationsVO1.
     * @return DirectRelationsVO1
     */
    public ViewObjectImpl getDirectRelationsVO1() {
        return (ViewObjectImpl)findViewObject("DirectRelationsVO1");
    }

    /**
     * Container's getter for MQDiffVO1.
     * @return MQDiffVO1
     */
    public ViewObjectImpl getMQDiffVO1() {
        return (ViewObjectImpl)findViewObject("MQDiffVO1");
    }

    /**
     * Container's getter for MQListVO1.
     * @return MQListVO1
     */
    public ViewObjectImpl getMQListRightVO1() {
        return (ViewObjectImpl)findViewObject("MQListRightVO1");
    }
}
