package com.dbms.csmq.model.NMQ;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 07 12:09:24 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NMQExtentionListVORowImpl extends ViewRowImpl {


    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LongValue {
            public Object get(NMQExtentionListVORowImpl obj) {
                return obj.getLongValue();
            }

            public void put(NMQExtentionListVORowImpl obj, Object value) {
                obj.setLongValue((String)value);
            }
        }
        ,
        RefCodelistValueShortVal {
            public Object get(NMQExtentionListVORowImpl obj) {
                return obj.getRefCodelistValueShortVal();
            }

            public void put(NMQExtentionListVORowImpl obj, Object value) {
                obj.setRefCodelistValueShortVal((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(NMQExtentionListVORowImpl object);

        public abstract void put(NMQExtentionListVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LONGVALUE = AttributesEnum.LongValue.index();
    public static final int REFCODELISTVALUESHORTVAL = AttributesEnum.RefCodelistValueShortVal.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NMQExtentionListVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute LongValue.
     * @return the LongValue
     */
    public String getLongValue() {
        return (String) getAttributeInternal(LONGVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LongValue.
     * @param value value to set the  LongValue
     */
    public void setLongValue(String value) {
        setAttributeInternal(LONGVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RefCodelistValueShortVal.
     * @return the RefCodelistValueShortVal
     */
    public String getRefCodelistValueShortVal() {
        return (String) getAttributeInternal(REFCODELISTVALUESHORTVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RefCodelistValueShortVal.
     * @param value value to set the  RefCodelistValueShortVal
     */
    public void setRefCodelistValueShortVal(String value) {
        setAttributeInternal(REFCODELISTVALUESHORTVAL, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }


}
