package com.dbms.csmq.model.NMQ;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 07 12:09:25 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NMQExtentionListVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NMQExtentionListVOImpl() {
    }
}
