package com.dbms.csmq.model.NMQ;

//import com.dbms.csmq.model.search.SearchModuleImpl;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 10 02:09:39 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NMQModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NMQModuleImpl() {
    }
    
    
 /*  public int loadContent (String dictShortName, String predictGroups, String term, String product, String level,
                          String category, String value1, String value4, String value2, String status) {

     /*

       PROCEDURE smq_bdl_utils_phase2.load_content
         (psmq_dct_nm        IN tms.tms_def_dictionaries.short_name%TYPE,
          psmq_grp_nm        IN tms.tms_predict_groups.name%TYPE,
          pmq_name           IN tms.tms_predict_contents.term%TYPE,
          pmq_product        IN tms.tms_predict_contents.value_3%TYPE,
          pmq_level          IN tms.tms_def_levels.name%TYPE,
          pmq_scp            IN tms.tms_predict_contents.category%TYPE,
          pmq_algo           IN tms.tms_predict_contents.value_1%TYPE,
          pmq_crtev          IN tms.tms_predict_contents.value_4%TYPE,
          pmq_group          IN tms.tms_predict_contents.value_2%TYPE,
          pstatus            IN tms.tms_predict_contents.status%TYPE --I, U
         )




    int result = -1;



    String sql = "BEGIN smq_bdl_utils_phase2.load_content(:psmq_dct_nm, :psmq_grp_nm, :pmq_name, :pmq_product, :pmq_level, :pmq_scp, :pmq_algo, :pmq_crtev, :pmq_group, :pstatus); end;";
      CallableStatement statement = getDBTransaction().createCallableStatement(sql, this.getDBTransaction().DEFAULT);

      try {
          statement.setObject ("psmq_dct_nm",dictShortName);
          statement.setObject ("psmq_grp_nm",predictGroups);
          statement.setObject ("pmq_name",term);
          statement.setObject ("pmq_product",product);
          statement.setObject ("pmq_level",level);
          statement.setNull("pmq_scp", Types.VARCHAR);
          statement.setObject ("pmq_algo",value1);
          statement.setNull("pmq_crtev", Types.VARCHAR);
          statement.setNull ("pmq_group",Types.VARCHAR);
          statement.setNull ("pstatus", Types.VARCHAR);
          statement.execute();
          }
      catch (SQLException e) {
          throw new JboException(e);
        }
      finally {
          if (statement != null) {
              try {
                statement.close();
              }
              catch (SQLException e) {}
            }

      }
      return result;
    }

     */

    /**
     * Container's getter for NMQCode1.
     * @return NMQCode1
     */
    public ViewObjectImpl getNMQCode1() {
        return (ViewObjectImpl)findViewObject("NMQCode1");
    }

    /**
     * Container's getter for NMQExtentionListVO1.
     * @return NMQExtentionListVO1
     */
    public NMQExtentionListVOImpl getNMQExtentionListVO1() {
        return (NMQExtentionListVOImpl)findViewObject("NMQExtentionListVO1");
    }

}
