package com.dbms.csmq.model.releaseGroups;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 09 10:41:32 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReleaseGroupsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ReleaseGroupsVOImpl() {
    }


    /**
     * Returns the bind variable value for dictShortName.
     * @return bind variable value for dictShortName
     */
    public String getdictShortName() {
        return (String)getNamedWhereClauseParam("dictShortName");
    }

    /**
     * Sets <code>value</code> for bind variable dictShortName.
     * @param value value to bind as dictShortName
     */
    public void setdictShortName(String value) {
        setNamedWhereClauseParam("dictShortName", value);
    }
}
