package com.dbms.csmq.model.releaseGroups;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 09 10:41:32 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ReleaseGroupsVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ActGroupNm {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getActGroupNm();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setActGroupNm((String)value);
            }
        }
        ,
        ActGroupDesc {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getActGroupDesc();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setActGroupDesc((String)value);
            }
        }
        ,
        ActGroupId {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getActGroupId();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setActGroupId((Number)value);
            }
        }
        ,
        DctNm {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getDctNm();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setDctNm((String)value);
            }
        }
        ,
        Name {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getName();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setName((String)value);
            }
        }
        ,
        Description {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        PredictGroupId {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getPredictGroupId();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setPredictGroupId((Number)value);
            }
        }
        ,
        ShortName {
            public Object get(ReleaseGroupsVORowImpl obj) {
                return obj.getShortName();
            }

            public void put(ReleaseGroupsVORowImpl obj, Object value) {
                obj.setShortName((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ReleaseGroupsVORowImpl object);

        public abstract void put(ReleaseGroupsVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ACTGROUPNM = AttributesEnum.ActGroupNm.index();
    public static final int ACTGROUPDESC = AttributesEnum.ActGroupDesc.index();
    public static final int ACTGROUPID = AttributesEnum.ActGroupId.index();
    public static final int DCTNM = AttributesEnum.DctNm.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int PREDICTGROUPID = AttributesEnum.PredictGroupId.index();
    public static final int SHORTNAME = AttributesEnum.ShortName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ReleaseGroupsVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute ActGroupNm.
     * @return the ActGroupNm
     */
    public String getActGroupNm() {
        return (String) getAttributeInternal(ACTGROUPNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActGroupNm.
     * @param value value to set the  ActGroupNm
     */
    public void setActGroupNm(String value) {
        setAttributeInternal(ACTGROUPNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActGroupDesc.
     * @return the ActGroupDesc
     */
    public String getActGroupDesc() {
        return (String) getAttributeInternal(ACTGROUPDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActGroupDesc.
     * @param value value to set the  ActGroupDesc
     */
    public void setActGroupDesc(String value) {
        setAttributeInternal(ACTGROUPDESC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActGroupId.
     * @return the ActGroupId
     */
    public Number getActGroupId() {
        return (Number) getAttributeInternal(ACTGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActGroupId.
     * @param value value to set the  ActGroupId
     */
    public void setActGroupId(Number value) {
        setAttributeInternal(ACTGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DctNm.
     * @return the DctNm
     */
    public String getDctNm() {
        return (String) getAttributeInternal(DCTNM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DctNm.
     * @param value value to set the  DctNm
     */
    public void setDctNm(String value) {
        setAttributeInternal(DCTNM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Name.
     * @return the Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Name.
     * @param value value to set the  Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PredictGroupId.
     * @return the PredictGroupId
     */
    public Number getPredictGroupId() {
        return (Number) getAttributeInternal(PREDICTGROUPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PredictGroupId.
     * @param value value to set the  PredictGroupId
     */
    public void setPredictGroupId(Number value) {
        setAttributeInternal(PREDICTGROUPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ShortName.
     * @return the ShortName
     */
    public String getShortName() {
        return (String) getAttributeInternal(SHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ShortName.
     * @param value value to set the  ShortName
     */
    public void setShortName(String value) {
        setAttributeInternal(SHORTNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
