package com.dbms.csmq.model.search;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 04 12:37:01 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EntryTSListVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        EndTsString {
            public Object get(EntryTSListVORowImpl obj) {
                return obj.getEndTsString();
            }

            public void put(EntryTSListVORowImpl obj, Object value) {
                obj.setEndTsString((String)value);
            }
        }
        ,
        EndTs {
            public Object get(EntryTSListVORowImpl obj) {
                return obj.getEndTs();
            }

            public void put(EntryTSListVORowImpl obj, Object value) {
                obj.setEndTs((Date)value);
            }
        }
        ,
        DateRange {
            public Object get(EntryTSListVORowImpl obj) {
                return obj.getDateRange();
            }

            public void put(EntryTSListVORowImpl obj, Object value) {
                obj.setDateRange((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(EntryTSListVORowImpl object);

        public abstract void put(EntryTSListVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ENDTSSTRING = AttributesEnum.EndTsString.index();
    public static final int ENDTS = AttributesEnum.EndTs.index();
    public static final int DATERANGE = AttributesEnum.DateRange.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EntryTSListVORowImpl() {
    }


    /**
     * Gets the attribute value for the calculated attribute EndTsString.
     * @return the EndTsString
     */
    public String getEndTsString() {
        return (String) getAttributeInternal(ENDTSSTRING);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndTsString.
     * @param value value to set the  EndTsString
     */
    public void setEndTsString(String value) {
        setAttributeInternal(ENDTSSTRING, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EndTs.
     * @return the EndTs
     */
    public Date getEndTs() {
        return (Date) getAttributeInternal(ENDTS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EndTs.
     * @param value value to set the  EndTs
     */
    public void setEndTs(Date value) {
        setAttributeInternal(ENDTS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DateRange.
     * @return the DateRange
     */
    public String getDateRange() {
        return (String) getAttributeInternal(DATERANGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DateRange.
     * @param value value to set the  DateRange
     */
    public void setDateRange(String value) {
        setAttributeInternal(DATERANGE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
