package com.dbms.csmq.model.search;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 08 08:39:38 EDT 2013
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HierarchySourceTermSearchFixVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HierarchySourceTermSearchFixVOImpl() {
    }

    /**
     * Returns the bind variable value for dictShortName.
     * @return bind variable value for dictShortName
     */
    public String getdictShortName() {
        return (String)getNamedWhereClauseParam("dictShortName");
    }

    /**
     * Sets <code>value</code> for bind variable dictShortName.
     * @param value value to bind as dictShortName
     */
    public void setdictShortName(String value) {
        setNamedWhereClauseParam("dictShortName", value);
    }

    /**
     * Returns the bind variable value for term.
     * @return bind variable value for term
     */
    public String getterm() {
        return (String)getNamedWhereClauseParam("term");
    }

    /**
     * Sets <code>value</code> for bind variable term.
     * @param value value to bind as term
     */
    public void setterm(String value) {
        setNamedWhereClauseParam("term", value);
    }

    /**
     * Returns the bind variable value for startDate.
     * @return bind variable value for startDate
     */
    public String getstartDate() {
        return (String)getNamedWhereClauseParam("startDate");
    }

    /**
     * Sets <code>value</code> for bind variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(String value) {
        setNamedWhereClauseParam("startDate", value);
    }

    /**
     * Returns the bind variable value for endDate.
     * @return bind variable value for endDate
     */
    public String getendDate() {
        return (String)getNamedWhereClauseParam("endDate");
    }

    /**
     * Sets <code>value</code> for bind variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(String value) {
        setNamedWhereClauseParam("endDate", value);
    }

    /**
     * Returns the bind variable value for activityStatus.
     * @return bind variable value for activityStatus
     */
    public String getactivityStatus() {
        return (String)getNamedWhereClauseParam("activityStatus");
    }

    /**
     * Sets <code>value</code> for bind variable activityStatus.
     * @param value value to bind as activityStatus
     */
    public void setactivityStatus(String value) {
        setNamedWhereClauseParam("activityStatus", value);
    }

    /**
     * Returns the bind variable value for releaseStatus.
     * @return bind variable value for releaseStatus
     */
    public String getreleaseStatus() {
        return (String)getNamedWhereClauseParam("releaseStatus");
    }

    /**
     * Sets <code>value</code> for bind variable releaseStatus.
     * @param value value to bind as releaseStatus
     */
    public void setreleaseStatus(String value) {
        setNamedWhereClauseParam("releaseStatus", value);
    }

    /**
     * Returns the bind variable value for activationGroup.
     * @return bind variable value for activationGroup
     */
    public String getactivationGroup() {
        return (String)getNamedWhereClauseParam("activationGroup");
    }

    /**
     * Sets <code>value</code> for bind variable activationGroup.
     * @param value value to bind as activationGroup
     */
    public void setactivationGroup(String value) {
        setNamedWhereClauseParam("activationGroup", value);
    }

    /**
     * Returns the bind variable value for MQGroup.
     * @return bind variable value for MQGroup
     */
    public String getMQGroup() {
        return (String)getNamedWhereClauseParam("MQGroup");
    }

    /**
     * Sets <code>value</code> for bind variable MQGroup.
     * @param value value to bind as MQGroup
     */
    public void setMQGroup(String value) {
        setNamedWhereClauseParam("MQGroup", value);
    }

    /**
     * Returns the bind variable value for levelName.
     * @return bind variable value for levelName
     */
    public String getlevelName() {
        return (String)getNamedWhereClauseParam("levelName");
    }

    /**
     * Sets <code>value</code> for bind variable levelName.
     * @param value value to bind as levelName
     */
    public void setlevelName(String value) {
        setNamedWhereClauseParam("levelName", value);
    }

    /**
     * Returns the bind variable value for MQCode.
     * @return bind variable value for MQCode
     */
    public String getMQCode() {
        return (String)getNamedWhereClauseParam("MQCode");
    }

    /**
     * Sets <code>value</code> for bind variable MQCode.
     * @param value value to bind as MQCode
     */
    public void setMQCode(String value) {
        setNamedWhereClauseParam("MQCode", value);
    }

    /**
     * Returns the bind variable value for MQCriticalEvent.
     * @return bind variable value for MQCriticalEvent
     */
    public String getMQCriticalEvent() {
        return (String)getNamedWhereClauseParam("MQCriticalEvent");
    }

    /**
     * Sets <code>value</code> for bind variable MQCriticalEvent.
     * @param value value to bind as MQCriticalEvent
     */
    public void setMQCriticalEvent(String value) {
        setNamedWhereClauseParam("MQCriticalEvent", value);
    }

    /**
     * Returns the bind variable value for uniqueIDsOnly.
     * @return bind variable value for uniqueIDsOnly
     */
    public String getuniqueIDsOnly() {
        return (String)getNamedWhereClauseParam("uniqueIDsOnly");
    }

    /**
     * Sets <code>value</code> for bind variable uniqueIDsOnly.
     * @param value value to bind as uniqueIDsOnly
     */
    public void setuniqueIDsOnly(String value) {
        setNamedWhereClauseParam("uniqueIDsOnly", value);
    }

    /**
     * Returns the bind variable value for filterForUser.
     * @return bind variable value for filterForUser
     */
    public String getfilterForUser() {
        return (String)getNamedWhereClauseParam("filterForUser");
    }

    /**
     * Sets <code>value</code> for bind variable filterForUser.
     * @param value value to bind as filterForUser
     */
    public void setfilterForUser(String value) {
        setNamedWhereClauseParam("filterForUser", value);
    }

    /**
     * Returns the bind variable value for currentUser.
     * @return bind variable value for currentUser
     */
    public String getcurrentUser() {
        return (String)getNamedWhereClauseParam("currentUser");
    }

    /**
     * Sets <code>value</code> for bind variable currentUser.
     * @param value value to bind as currentUser
     */
    public void setcurrentUser(String value) {
        setNamedWhereClauseParam("currentUser", value);
    }

    /**
     * Returns the bind variable value for killSwitch.
     * @return bind variable value for killSwitch
     */
    public Integer getkillSwitch() {
        return (Integer)getNamedWhereClauseParam("killSwitch");
    }

    /**
     * Sets <code>value</code> for bind variable killSwitch.
     * @param value value to bind as killSwitch
     */
    public void setkillSwitch(Integer value) {
        setNamedWhereClauseParam("killSwitch", value);
    }

    /**
     * Returns the bind variable value for showNarrowScpOnly.
     * @return bind variable value for showNarrowScpOnly
     */
    public String getshowNarrowScpOnly() {
        return (String)getNamedWhereClauseParam("showNarrowScpOnly");
    }

    /**
     * Sets <code>value</code> for bind variable showNarrowScpOnly.
     * @param value value to bind as showNarrowScpOnly
     */
    public void setshowNarrowScpOnly(String value) {
        setNamedWhereClauseParam("showNarrowScpOnly", value);
    }

    /**
     * Returns the bind variable value for MQScope.
     * @return bind variable value for MQScope
     */
    public String getMQScope() {
        return (String)getNamedWhereClauseParam("MQScope");
    }

    /**
     * Sets <code>value</code> for bind variable MQScope.
     * @param value value to bind as MQScope
     */
    public void setMQScope(String value) {
        setNamedWhereClauseParam("MQScope", value);
    }

    /**
     * Returns the bind variable value for pState.
     * @return bind variable value for pState
     */
    public String getpState() {
        return (String)getNamedWhereClauseParam("pState");
    }

    /**
     * Sets <code>value</code> for bind variable pState.
     * @param value value to bind as pState
     */
    public void setpState(String value) {
        setNamedWhereClauseParam("pState", value);
    }

    /**
     * Returns the bind variable value for pUserRole.
     * @return bind variable value for pUserRole
     */
    public String getpUserRole() {
        return (String)getNamedWhereClauseParam("pUserRole");
    }

    /**
     * Sets <code>value</code> for bind variable pUserRole.
     * @param value value to bind as pUserRole
     */
    public void setpUserRole(String value) {
        setNamedWhereClauseParam("pUserRole", value);
    }

    /**
     * Returns the bind variable value for pMode.
     * @return bind variable value for pMode
     */
    public Number getpMode() {
        return (Number)getNamedWhereClauseParam("pMode");
    }

    /**
     * Sets <code>value</code> for bind variable pMode.
     * @param value value to bind as pMode
     */
    public void setpMode(Number value) {
        setNamedWhereClauseParam("pMode", value);
    }

    /**
     * Returns the bind variable value for pApprove.
     * @return bind variable value for pApprove
     */
    public String getpApprove() {
        return (String)getNamedWhereClauseParam("pApprove");
    }

    /**
     * Sets <code>value</code> for bind variable pApprove.
     * @param value value to bind as pApprove
     */
    public void setpApprove(String value) {
        setNamedWhereClauseParam("pApprove", value);
    }

    /**
     * Returns the bind variable value for psVirtualDictionaryName.
     * @return bind variable value for psVirtualDictionaryName
     */
    public String getpsVirtualDictionaryName() {
        return (String)getNamedWhereClauseParam("psVirtualDictionaryName");
    }

    /**
     * Sets <code>value</code> for bind variable psVirtualDictionaryName.
     * @param value value to bind as psVirtualDictionaryName
     */
    public void setpsVirtualDictionaryName(String value) {
        setNamedWhereClauseParam("psVirtualDictionaryName", value);
    }
}
