package com.dbms.csmq.model.search;

import java.sql.ResultSet;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 09 15:19:07 EDT 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SimpleSearchImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SimpleSearchImpl() {}

    /**
     * Returns the bind variable value for dictName.
     * @return bind variable value for dictName
     */
    public String getdictName() {
        return (String)getNamedWhereClauseParam("dictName");
    }

    /**
     * Sets <code>value</code> for bind variable dictName.
     * @param value value to bind as dictName
     */
    public void setdictName(String value) {
        setNamedWhereClauseParam("dictName", value);
    }

    /**
     * Returns the bind variable value for startDate.
     * @return bind variable value for startDate
     */
    public String getstartDate() {
        return (String)getNamedWhereClauseParam("startDate");
    }

    /**
     * Sets <code>value</code> for bind variable startDate.
     * @param value value to bind as startDate
     */
    public void setstartDate(String value) {
        setNamedWhereClauseParam("startDate", value);
    }

    /**
     * Returns the bind variable value for endDate.
     * @return bind variable value for endDate
     */
    public String getendDate() {
        return (String)getNamedWhereClauseParam("endDate");
    }

    /**
     * Sets <code>value</code> for bind variable endDate.
     * @param value value to bind as endDate
     */
    public void setendDate(String value) {
        setNamedWhereClauseParam("endDate", value);
    }

    /**
     * Returns the bind variable value for term.
     * @return bind variable value for term
     */
    public String getterm() {
        return (String)getNamedWhereClauseParam("term");
    }

    /**
     * Sets <code>value</code> for bind variable term.
     * @param value value to bind as term
     */
    public void setterm(String value) {
        setNamedWhereClauseParam("term", value);
    }


    /**
     * Returns the bind variable value for state.
     * @return bind variable value for state
     */
    public String getstate() {
        return (String)getNamedWhereClauseParam("state");
    }

    /**
     * Sets <code>value</code> for bind variable state.
     * @param value value to bind as state
     */
    public void setstate(String value) {
        setNamedWhereClauseParam("state", value);
    }

    /**
     * Returns the bind variable value for mqGroup.
     * @return bind variable value for mqGroup
     */
    public String getmqGroup() {
        return (String)getNamedWhereClauseParam("mqGroup");
    }

    /**
     * Sets <code>value</code> for bind variable mqGroup.
     * @param value value to bind as mqGroup
     */
    public void setmqGroup(String value) {
        setNamedWhereClauseParam("mqGroup", value);
    }

    /**
     * Returns the bind variable value for activityStatus.
     * @return bind variable value for activityStatus
     */
    public String getactivityStatus() {
        return (String)getNamedWhereClauseParam("activityStatus");
    }

    /**
     * Sets <code>value</code> for bind variable activityStatus.
     * @param value value to bind as activityStatus
     */
    public void setactivityStatus(String value) {
        setNamedWhereClauseParam("activityStatus", value);
    }

    /**
     * Returns the bind variable value for dictShortName.
     * @return bind variable value for dictShortName
     */
    public String getdictShortName() {
        return (String)getNamedWhereClauseParam("dictShortName");
    }

    /**
     * Sets <code>value</code> for bind variable dictShortName.
     * @param value value to bind as dictShortName
     */
    public void setdictShortName(String value) {
        setNamedWhereClauseParam("dictShortName", value);
    }

    /**
     * Returns the bind variable value for currentPendingStatus.
     * @return bind variable value for currentPendingStatus
     */
    public String getcurrentPendingStatus() {
        return (String)getNamedWhereClauseParam("currentPendingStatus");
    }

    /**
     * Sets <code>value</code> for bind variable currentPendingStatus.
     * @param value value to bind as currentPendingStatus
     */
    public void setcurrentPendingStatus(String value) {
        setNamedWhereClauseParam("currentPendingStatus", value);
    }

    /**
     * Returns the bind variable value for activationGroup.
     * @return bind variable value for activationGroup
     */
    public String getactivationGroup() {
        return (String)getNamedWhereClauseParam("activationGroup");
    }

    /**
     * Sets <code>value</code> for bind variable activationGroup.
     * @param value value to bind as activationGroup
     */
    public void setactivationGroup(String value) {
        setNamedWhereClauseParam("activationGroup", value);
    }

    /**
     * Returns the bind variable value for MQGroup.
     * @return bind variable value for MQGroup
     */
    public String getMQGroup() {
        return (String)getNamedWhereClauseParam("MQGroup");
    }

    /**
     * Sets <code>value</code> for bind variable MQGroup.
     * @param value value to bind as MQGroup
     */
    public void setMQGroup(String value) {
        setNamedWhereClauseParam("MQGroup", value);
    }

    /**
     * Returns the bind variable value for releaseStatus.
     * @return bind variable value for releaseStatus
     */
    public String getreleaseStatus() {
        return (String)getNamedWhereClauseParam("releaseStatus");
    }

    /**
     * Sets <code>value</code> for bind variable releaseStatus.
     * @param value value to bind as releaseStatus
     */
    public void setreleaseStatus(String value) {
        setNamedWhereClauseParam("releaseStatus", value);
    }

    /**
     * executeQueryForCollection - overridden for custom java data source support.
     */
    protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams) {
        super.executeQueryForCollection(qc, params, noUserParams);
    }

    /**
     * hasNextForCollection - overridden for custom java data source support.
     */
    protected boolean hasNextForCollection(Object qc) {
        boolean bRet = super.hasNextForCollection(qc);
        return bRet;
    }

    /**
     * createRowFromResultSet - overridden for custom java data source support.
     */
    protected ViewRowImpl createRowFromResultSet(Object qc, ResultSet resultSet) {
        ViewRowImpl value = super.createRowFromResultSet(qc, resultSet);
        return value;
    }

    /**
     * getQueryHitCount - overridden for custom java data source support.
     */
    public long getQueryHitCount(ViewRowSetImpl viewRowSet) {
        long value = super.getQueryHitCount(viewRowSet);
        return value;
    }
}
