package com.dbms.csmq.model.product.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 29 18:58:50 EDT 2014
// ---------------------------------------------------------------------
public interface ProductModule extends ApplicationModule {
    
}
